import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Link, useParams } from "wouter";
import { ArrowLeft, Loader2, CheckCircle, Download, ExternalLink, Shield, FileDown, FileText } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { LEGAL_SOURCES } from "@shared/types";
import { useT } from "@/i18n";

const RISK_COLORS = {
  high: "bg-red-100 text-red-800 border-red-200",
  medium: "bg-amber-100 text-amber-800 border-amber-200",
  low: "bg-green-100 text-green-800 border-green-200",
};
const TX = {
  sk: {
    riskLabels: { high: "Vysoké riziko", medium: "Stredné riziko", low: "Nízke riziko" } as Record<string, string>,
    pdfError: "Chyba pri generovaní PDF",
    pdfSuccess: "PDF bol úspešne vygenerovaný",
    pdfSuccessDesc: "Súbor sa stiahol do vašich súborov.",
    pdfDownloadFail: "Nepodarilo sa stiahnuť PDF",
    pdfErrorToast: "Chyba pri sťahovaní PDF",
    generating: "Generujem PDF...",
    downloadPdf: "Stiahnuť report (PDF)",
    downloadDocx: "Stiahnuť s revíziami (DOCX)",
    docxSuccess: "DOCX bol úspešne vygenerovaný",
    docxSuccessDesc: "Otvorte v MS Word a použite Revízie → Prijať/Odmietnuť.",
    docxError: "Chyba pri generovaní DOCX",
    docxErrorToast: "Chyba pri sťahovaní DOCX",
    generatingDocx: "Generujem DOCX...",
    showRedline: "Zobraziť navrhované zmeny",
    hideRedline: "Skryť navrhované zmeny",
    redlineOriginal: "Pôvodné znenie:",
    redlineProposed: "Navrhované znenie:",
    notAvailable: "Report ešte nie je k dispozícii.",
    backToDashboard: "Späť na prehľad",
    title: "Analýza zmluvy",
    verifiedByLawyer: "Overené advokátom",
    signed: "Podpísané",
    highRisk: "Vysoké riziko",
    mediumRisk: "Stredné riziko",
    lowRisk: "Nízke riziko",
    summary: "Zhrnutie",
    recommendation: "Odporúčanie",
    detailedFindings: (n: number) => `Detailné nálezy (${n} klauzúl)`,
    legalBasis: "Právny základ:",
    suggestedEdit: "Navrhovaná úprava:",
    lawyerNote: "Poznámka advokáta:",
    freePreviewTitle: "Toto je bezplatný náhľad",
    freePreviewDesc: "Vidíte iba 3 najzávažnejšie riziká. Plný report obsahuje analýzu všetkých klauzúl, právne základy, navrhované úpravy a overenie advokátom.",
    orderFull: "Objednať plný report od 249 eur",
    legalSources: "Použité právne zdroje",
    disclaimer1: "Tento report bol vygenerovaný systémom bod.legal s využitím AI a overený advokátom.",
    disclaimer2: "Prevádzkované KILIAN LEGAL s.r.o. · IČO: 53 957 008",
    dateLocale: "sk-SK",
  },
  en: {
    riskLabels: { high: "High risk", medium: "Medium risk", low: "Low risk" } as Record<string, string>,
    pdfError: "Error generating PDF",
    pdfSuccess: "PDF generated successfully",
    pdfSuccessDesc: "The file has been downloaded to your files.",
    pdfDownloadFail: "Failed to download PDF",
    pdfErrorToast: "Error downloading PDF",
    generating: "Generating PDF...",
    downloadPdf: "Download report (PDF)",
    downloadDocx: "Download with track changes (DOCX)",
    docxSuccess: "DOCX generated successfully",
    docxSuccessDesc: "Open in MS Word and use Review → Accept/Reject.",
    docxError: "Error generating DOCX",
    docxErrorToast: "Error downloading DOCX",
    generatingDocx: "Generating DOCX...",
    showRedline: "Show proposed changes",
    hideRedline: "Hide proposed changes",
    redlineOriginal: "Original text:",
    redlineProposed: "Proposed text:",
    notAvailable: "The report is not available yet.",
    backToDashboard: "Back to dashboard",
    title: "Contract analysis",
    verifiedByLawyer: "Verified by lawyer",
    signed: "Signed",
    highRisk: "High risk",
    mediumRisk: "Medium risk",
    lowRisk: "Low risk",
    summary: "Summary",
    recommendation: "Recommendation",
    detailedFindings: (n: number) => `Detailed findings (${n} clauses)`,
    legalBasis: "Legal basis:",
    suggestedEdit: "Suggested amendment:",
    lawyerNote: "Lawyer's note:",
    freePreviewTitle: "This is a free preview",
    freePreviewDesc: "You only see the 3 most serious risks. The full report includes analysis of all clauses, legal grounds, suggested amendments, and lawyer verification.",
    orderFull: "Order the full report from 249 eur",
    legalSources: "Legal sources used",
    disclaimer1: "This report was generated by the bod.legal system using AI and verified by a lawyer.",
    disclaimer2: "Operated by KILIAN LEGAL s.r.o. · Company ID: 53 957 008",
    dateLocale: "en-GB",
  },
};

function DownloadPdfButton({ contractId, tx }: { contractId: number; tx: typeof TX.sk }) {
  const { locale } = useT();
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleDownload = async () => {
    setDownloading(true);
    setError(null);
    try {
      const response = await fetch(`/api/contracts/${contractId}/report.pdf?lang=${locale}`, {
        credentials: "include",
      });
      if (!response.ok) {
        const errData = await response.json().catch(() => ({ error: tx.pdfError }));
        throw new Error(errData.error || tx.pdfError);
      }
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      const disposition = response.headers.get("Content-Disposition");
      const filenameMatch = disposition?.match(/filename="(.+?)"/);
      a.download = filenameMatch?.[1] || `bod-legal_report_${contractId}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast.success(tx.pdfSuccess, {
        description: tx.pdfSuccessDesc,
      });
    } catch (err: any) {
      const msg = err.message || tx.pdfDownloadFail;
      setError(msg);
      toast.error(tx.pdfErrorToast, {
        description: msg,
      });
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="text-center">
      <Button className="font-sans" onClick={handleDownload} disabled={downloading}>
        {downloading ? (
          <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> {tx.generating}</>
        ) : (
          <><FileDown className="mr-2 h-4 w-4" /> {tx.downloadPdf}</>
        )}
      </Button>
      {error && <p className="text-sm text-red-600 font-sans mt-2">{error}</p>}
    </div>
  );
}

function DownloadDocxButton({ contractId, tx }: { contractId: number; tx: typeof TX.sk }) {
  const { locale } = useT();
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleDownload = async () => {
    setDownloading(true);
    setError(null);
    try {
      const response = await fetch(`/api/contracts/${contractId}/report.docx?lang=${locale}`, {
        credentials: "include",
      });
      if (!response.ok) {
        const errData = await response.json().catch(() => ({ error: tx.docxError }));
        throw new Error(errData.error || tx.docxError);
      }
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      const disposition = response.headers.get("Content-Disposition");
      const filenameMatch = disposition?.match(/filename="(.+?)"/);
      a.download = filenameMatch?.[1] || `bod-legal_report_${contractId}.docx`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast.success(tx.docxSuccess, {
        description: tx.docxSuccessDesc,
      });
    } catch (err: any) {
      const msg = err.message || tx.docxError;
      setError(msg);
      toast.error(tx.docxErrorToast, {
        description: msg,
      });
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="text-center">
      <Button variant="outline" className="font-sans" onClick={handleDownload} disabled={downloading}>
        {downloading ? (
          <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> {tx.generatingDocx}</>
        ) : (
          <><FileText className="mr-2 h-4 w-4" /> {tx.downloadDocx}</>
        )}
      </Button>
      {error && <p className="text-sm text-red-600 font-sans mt-2">{error}</p>}
    </div>
  );
}

export default function Report() {
  const { isAuthenticated } = useAuth({ redirectOnUnauthenticated: true });
  const { locale, localePath } = useT();
  const tx = TX[locale];
  const params = useParams<{ id: string }>();
  const contractId = parseInt(params.id || "0");

  const { data, isLoading } = trpc.contracts.getById.useQuery(
    { id: contractId },
    { enabled: isAuthenticated && contractId > 0 }
  );

  if (isLoading) {
    return (
      <div className="min-h-screen flex flex-col">
        <Header />
        <main className="flex-1 flex items-center justify-center">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
        </main>
      </div>
    );
  }

  if (!data || !data.report) {
    return (
      <div className="min-h-screen flex flex-col">
        <Header />
        <main className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <p className="text-muted-foreground font-sans mb-4">{tx.notAvailable}</p>
            <Link href={localePath("/dashboard")}><Button variant="ghost" className="font-sans">{tx.backToDashboard}</Button></Link>
          </div>
        </main>
      </div>
    );
  }

  const { contract, clauses, report, isLimited } = data;
  const riskSummary = report.riskSummary as { high: number; medium: number; low: number } | null;
  const [showRedline, setShowRedline] = useState(false);
  const hasRedlineContent = clauses?.some((c) => c.excerpt && c.suggestedEdit);

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1 py-12">
        <div className="container max-w-4xl">
          <Link href={localePath("/dashboard")}>
            <Button variant="ghost" size="sm" className="font-sans mb-4">
              <ArrowLeft className="mr-1 h-4 w-4" /> {tx.backToDashboard}
            </Button>
          </Link>

          {/* Report Header */}
          <div className="mb-8">
            <div className="flex items-start justify-between">
              <div>
                <h1 className="text-3xl font-serif mb-2">{tx.title}</h1>
                <p className="text-muted-foreground font-sans">{contract.fileName}</p>
              </div>
              {report.isSigned === 1 && (
                <Badge className="bg-green-100 text-green-800 border-green-200 font-sans">
                  <Shield className="mr-1 h-3 w-3" /> {tx.verifiedByLawyer}
                </Badge>
              )}
            </div>
            {report.isSigned === 1 && report.lawyerName && (
              <p className="text-sm text-muted-foreground font-sans mt-2">
                {tx.signed}: {report.lawyerName} · {report.signedAt ? new Date(report.signedAt).toLocaleDateString(tx.dateLocale) : ""}
              </p>
            )}
          </div>

          {/* Risk Summary Cards */}
          {riskSummary && (
            <div className="grid grid-cols-3 gap-4 mb-8">
              <Card className="border-red-200 bg-red-50">
                <CardContent className="p-4 text-center">
                  <p className="text-3xl font-serif text-red-800">{riskSummary.high}</p>
                  <p className="text-xs text-red-600 font-sans">{tx.highRisk}</p>
                </CardContent>
              </Card>
              <Card className="border-amber-200 bg-amber-50">
                <CardContent className="p-4 text-center">
                  <p className="text-3xl font-serif text-amber-800">{riskSummary.medium}</p>
                  <p className="text-xs text-amber-600 font-sans">{tx.mediumRisk}</p>
                </CardContent>
              </Card>
              <Card className="border-green-200 bg-green-50">
                <CardContent className="p-4 text-center">
                  <p className="text-3xl font-serif text-green-800">{riskSummary.low}</p>
                  <p className="text-xs text-green-600 font-sans">{tx.lowRisk}</p>
                </CardContent>
              </Card>
            </div>
          )}

          {/* Summary - hidden for basic plan */}
          {!isLimited && report.summary && (
            <Card className="mb-8">
              <CardContent className="p-6">
                <h2 className="font-serif text-xl mb-3">{tx.summary}</h2>
                <p className="font-sans text-sm leading-relaxed">{report.summary}</p>
              </CardContent>
            </Card>
          )}

          {/* Recommendation - hidden for basic plan */}
          {!isLimited && report.recommendation && (
            <Card className="mb-8 border-primary/20 bg-primary/[0.02]">
              <CardContent className="p-6">
                <h2 className="font-serif text-xl mb-3">{tx.recommendation}</h2>
                <p className="font-sans text-sm leading-relaxed">{report.recommendation}</p>
              </CardContent>
            </Card>
          )}

          {/* Clause Findings */}
          {clauses && clauses.length > 0 && (
            <div className="mb-8">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-serif">{tx.detailedFindings(clauses.length)}</h2>
                {!isLimited && hasRedlineContent && (
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setShowRedline(!showRedline)}
                    className={`font-sans text-xs gap-1.5 transition-colors ${showRedline ? 'border-primary/50 bg-primary/5 text-primary' : ''}`}
                  >
                    <FileText className="h-3.5 w-3.5" />
                    {showRedline ? tx.hideRedline : tx.showRedline}
                  </Button>
                )}
              </div>
              <div className="space-y-3">
                {clauses.map((clause) => {
                  const effectiveRisk = clause.overriddenRiskLevel || clause.riskLevel;
                  return (
                    <Card key={clause.id}>
                      <CardContent className="p-5">
                        <div className="flex items-start justify-between mb-2">
                          <div className="flex items-center gap-2">
                            <span className="text-xs text-muted-foreground font-sans">#{clause.clauseNumber}</span>
                            <h4 className="font-sans font-medium">{clause.title}</h4>
                          </div>
                          <Badge className={`${RISK_COLORS[effectiveRisk]} text-xs font-sans`}>
                            {tx.riskLabels[effectiveRisk]}
                          </Badge>
                        </div>
                        {clause.excerpt && (
                          <p className="text-sm text-muted-foreground font-sans mb-2 italic">"{clause.excerpt}"</p>
                        )}
                        <p className="text-sm font-sans mb-2">{clause.finding}</p>
                        {(clause as any).legalBasis && (
                          <div className="flex items-center gap-2 mt-2">
                            <span className="text-xs font-sans text-muted-foreground">{tx.legalBasis}</span>
                            {(clause as any).legalSourceUrl ? (
                              <a href={(clause as any).legalSourceUrl} target="_blank" rel="noopener noreferrer" className="text-xs font-sans text-primary hover:underline inline-flex items-center gap-1">
                                {(clause as any).legalBasis} <ExternalLink className="h-3 w-3" />
                              </a>
                            ) : (
                              <span className="text-xs font-sans">{(clause as any).legalBasis}</span>
                            )}
                          </div>
                        )}
                        {clause.suggestedEdit && !showRedline && (
                          <div className="bg-primary/5 rounded p-3 mt-2">
                            <p className="text-xs font-sans font-medium text-primary mb-1">{tx.suggestedEdit}</p>
                            <p className="text-sm font-sans">{clause.suggestedEdit}</p>
                          </div>
                        )}
                        {showRedline && clause.excerpt && clause.suggestedEdit && (
                          <div className="mt-3 rounded-lg border border-dashed border-muted-foreground/30 p-4 bg-muted/20">
                            <div className="mb-2">
                              <span className="text-[11px] font-sans font-semibold uppercase tracking-wider text-red-600/80">{tx.redlineOriginal}</span>
                              <p className="text-sm font-sans mt-1 line-through text-red-700/80 decoration-red-500/60">{clause.excerpt}</p>
                            </div>
                            <div className="border-t border-dashed border-muted-foreground/20 pt-2">
                              <span className="text-[11px] font-sans font-semibold uppercase tracking-wider text-green-700/80">{tx.redlineProposed}</span>
                              <p className="text-sm font-sans mt-1 text-green-800 underline decoration-green-600/50 underline-offset-2">{clause.suggestedEdit}</p>
                            </div>
                          </div>
                        )}
                        {showRedline && !clause.excerpt && clause.suggestedEdit && (
                          <div className="mt-3 rounded-lg border border-dashed border-muted-foreground/30 p-4 bg-muted/20">
                            <span className="text-[11px] font-sans font-semibold uppercase tracking-wider text-green-700/80">{tx.redlineProposed}</span>
                            <p className="text-sm font-sans mt-1 text-green-800 underline decoration-green-600/50 underline-offset-2">{clause.suggestedEdit}</p>
                          </div>
                        )}
                        {clause.lawyerAnnotation && (
                          <div className="bg-amber-50 rounded p-3 mt-2 border border-amber-200">
                            <p className="text-xs font-sans font-medium text-amber-800 mb-1">{tx.lawyerNote}</p>
                            <p className="text-sm font-sans">{clause.lawyerAnnotation}</p>
                          </div>
                        )}
                      </CardContent>
                    </Card>
                  );
                })}
              </div>
            </div>
          )}

          {/* Upgrade CTA for basic plan */}
          {isLimited && (
            <Card className="mb-8 border-primary/30 bg-primary/[0.03]">
              <CardContent className="p-6 text-center">
                <h3 className="font-serif text-lg mb-2">{tx.freePreviewTitle}</h3>
                <p className="text-sm text-muted-foreground font-sans mb-4">
                  {tx.freePreviewDesc}
                </p>
                <Link href={localePath("/upload")}>
                  <Button className="font-sans">{tx.orderFull}</Button>
                </Link>
              </CardContent>
            </Card>
          )}

          {/* Legal Sources */}
          {!isLimited && (
            <Card className="mb-8">
              <CardContent className="p-6">
                <h2 className="font-serif text-xl mb-4">{tx.legalSources}</h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {LEGAL_SOURCES.map((source) => (
                    <a
                      key={source.id}
                      href={source.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-2 p-3 rounded border hover:border-primary/30 transition-colors"
                    >
                      <ExternalLink className="h-4 w-4 text-primary shrink-0" />
                      <div className="min-w-0">
                        <p className="font-sans text-sm font-medium truncate">{source.name}</p>
                        <p className="text-xs text-muted-foreground font-sans">{source.instrument}</p>
                      </div>
                      <Badge variant="outline" className="text-xs font-sans shrink-0">{source.source}</Badge>
                    </a>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Download buttons - only for paid plans */}
          {!isLimited && (
            <div className="flex flex-col sm:flex-row gap-3 justify-center mb-8">
              <DownloadPdfButton contractId={contractId} tx={tx} />
              <DownloadDocxButton contractId={contractId} tx={tx} />
            </div>
          )}

          {/* Disclaimer */}
          <div className="text-center text-xs text-muted-foreground font-sans p-4 border rounded bg-muted/30">
            <p>{tx.disclaimer1}</p>
            <p className="mt-1">{tx.disclaimer2}</p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
