import type { Express, Request, Response } from "express";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  InsertedTextRun,
  DeletedTextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  TableRow,
  TableCell,
  Table,
  WidthType,
  ShadingType,
  Header,
  Footer,
  PageNumber,
  NumberFormat,
} from "docx";
import { sdk } from "./_core/sdk";
import { getContractById, getClausesByContractId, getReportByContractId, getDeepAnalysisByContract, isClauseExcluded } from "./db";
import { signOffLines } from "@shared/advokat";
import { aiOutputStatement, AI_MARKING_KEYWORDS, AI_MARKING_CREATOR } from "@shared/aiMarking";

type Lang = "sk" | "en";

const LABELS = {
  sk: {
    title: "Analýza zmluvy",
    subtitle: "AI kontrola s overením advokátskou kanceláriou alebo advokátom | bod.legal",
    subtitleUnsigned: "Pracovná verzia, čaká na overenie advokátskou kanceláriou alebo advokátom | bod.legal",
    document: "Dokument",
    plan: "Plán",
    date: "Dátum",
    verifiedBy: "Overil",
    riskSummary: "Sumár rizík",
    high: "Vysoké",
    medium: "Stredné",
    low: "Nízke",
    summary: "Zhrnutie",
    recommendation: "Odporúčanie",
    deepTitle: "Hĺbková analýza (Mike OS)",
    deepScore: "Celkové rizikové skóre",
    dealBreakersTitle: "Kritické riziká (deal-breakers)",
    missingTitle: "Chýbajúce ustanovenia",
    checklistTitle: "Kontrolný zoznam na rokovanie",
    verificationNotesTitle: "Poznámky z kontroly konzistencie",
    findings: "Detailné nálezy",
    legalBasis: "Právny základ",
    suggestedEdit: "Navrhovaná úprava",
    lawyerNote: "Poznámka advokáta",
    originalText: "Pôvodný text",
    proposedChange: "Navrhovaná zmena",
    trackChangesNote: "Tento dokument obsahuje sledované zmeny (Track Changes). Otvorte v Microsoft Word a použite Revízie → Prijať/Odmietnuť na spracovanie navrhovaných úprav.",
    finalTitle: "Finálna verzia zmluvy",
    finalSubtitle: "S aplikovanými zmenami | bod.legal",
    finalNote: "Tento dokument obsahuje finálne znenie klauzúl po schválení/odmietnutí navrhovaných zmien.",
    clauseText: "Znenie klauzuly",
    disclaimer: "Tento report bol vygenerovaný systémom bod.legal s využitím AI a overený advokátskou kanceláriou alebo advokátom.",
    disclaimerUnsigned: "Tento report vygenerovala AI systému bod.legal a čaká na overenie advokátskou kanceláriou alebo advokátom.",
    draftLabel: "PRACOVNÁ VERZIA",
    company: "KILIAN LEGAL s.r.o. | IČO: 53 957 008",
    planLabels: { basic: "Základná kontrola", standard: "Štandardná kontrola", premium: "Prémiová kontrola" } as Record<string, string>,
    riskLabels: { high: "Vysoké riziko", medium: "Stredné riziko", low: "Nízke riziko" } as Record<string, string>,
  },
  en: {
    title: "Contract Analysis",
    subtitle: "AI Review with Law Firm or Attorney Verification | bod.legal",
    subtitleUnsigned: "Draft version, awaiting law firm or attorney verification | bod.legal",
    document: "Document",
    plan: "Plan",
    date: "Date",
    verifiedBy: "Verified by",
    riskSummary: "Risk Summary",
    high: "High",
    medium: "Medium",
    low: "Low",
    summary: "Summary",
    recommendation: "Recommendation",
    deepTitle: "Deep Analysis (Mike OS)",
    deepScore: "Overall risk score",
    dealBreakersTitle: "Deal-breakers",
    missingTitle: "Missing provisions",
    checklistTitle: "Negotiation checklist",
    verificationNotesTitle: "Verification notes",
    findings: "Detailed Findings",
    legalBasis: "Legal basis",
    suggestedEdit: "Suggested edit",
    lawyerNote: "Lawyer note",
    originalText: "Original text",
    proposedChange: "Proposed change",
    trackChangesNote: "This document contains Track Changes. Open in Microsoft Word and use Review → Accept/Reject to process the suggested edits.",
    finalTitle: "Final Contract Version",
    finalSubtitle: "With applied changes | bod.legal",
    finalNote: "This document contains the final clause wording after accepting/rejecting proposed changes.",
    clauseText: "Clause text",
    disclaimer: "This report was generated by bod.legal using AI and verified by the law firm or an attorney.",
    disclaimerUnsigned: "This report was generated by the bod.legal AI system and is awaiting verification by the law firm or an attorney.",
    draftLabel: "DRAFT VERSION",
    company: "KILIAN LEGAL s.r.o. | IČO: 53 957 008",
    planLabels: { basic: "Basic Review", standard: "Standard Review", premium: "Premium Review" } as Record<string, string>,
    riskLabels: { high: "High risk", medium: "Medium risk", low: "Low risk" } as Record<string, string>,
  },
};

const AUTHOR = "bod.legal AI";
const REVISION_DATE = new Date().toISOString();

/**
 * Page header: unsigned documents carry a clearly visible draft label so a
 * working version can never be mistaken for a lawyer-verified report.
 */
function buildPageHeader(l: (typeof LABELS)["sk"], isSigned: boolean): Header {
  return new Header({
    children: [
      new Paragraph({
        children: isSigned
          ? [new TextRun({ text: "bod.legal", font: "Georgia", bold: true, size: 18, color: "999999" })]
          : [
              new TextRun({ text: l.draftLabel, font: "Georgia", bold: true, size: 18, color: "B45309" }),
              new TextRun({ text: " | bod.legal", font: "Georgia", bold: true, size: 18, color: "999999" }),
            ],
        alignment: AlignmentType.RIGHT,
      }),
    ],
  });
}

function riskColor(level: string): string {
  switch (level) {
    case "high": return "FF4444";
    case "medium": return "FF9900";
    case "low": return "44AA44";
    default: return "666666";
  }
}

/**
 * Generate a DOCX buffer with track changes for suggested edits.
 */
async function generateReportDocx(
  contract: any,
  clauses: any[],
  report: any,
  lang: Lang,
  deep: any = null
): Promise<Buffer> {
  const l = LABELS[lang];
  // Verification is only claimed once the lawyer signed the report.
  const isSigned = !!report.isSigned;
  const planLabel = l.planLabels[contract.plan] || contract.plan;
  const dateStr = new Date(contract.createdAt).toLocaleDateString(lang === "sk" ? "sk-SK" : "en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  // Sort clauses by clauseNumber
  const sortedClauses = [...clauses].sort((a, b) => a.clauseNumber - b.clauseNumber);

  // Risk counts
  const risks = { high: 0, medium: 0, low: 0 };
  sortedClauses.forEach((c) => {
    const level = (c.overriddenRiskLevel || c.riskLevel) as keyof typeof risks;
    if (risks[level] !== undefined) risks[level]++;
  });

  // Build document sections
  const children: Paragraph[] = [];

  // ─── Title ─────────────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      children: [new TextRun({ text: l.title, bold: true, size: 48, font: "Georgia" })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [new TextRun({ text: isSigned ? l.subtitle : l.subtitleUnsigned, size: 20, color: "666666" })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    })
  );

  // ─── Metadata ──────────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: `${l.document}: `, bold: true }),
        new TextRun({ text: contract.fileName || "…" }),
      ],
      spacing: { after: 80 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `${l.plan}: `, bold: true }),
        new TextRun({ text: planLabel }),
      ],
      spacing: { after: 80 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `${l.date}: `, bold: true }),
        new TextRun({ text: dateStr }),
      ],
      spacing: { after: 80 },
    })
  );

  if (isSigned && report.lawyerName) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: `${l.verifiedBy}: `, bold: true }),
          ...signOffLines(report.lawyerName, lang).map((line, i) =>
            new TextRun(i === 0 ? { text: line } : { text: line, break: 1 })
          ),
        ],
        spacing: { after: 200 },
      })
    );
  }

  // ─── Risk Summary ──────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: l.riskSummary })],
      spacing: { before: 300, after: 200 },
    })
  );

  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: `${l.high}: ${risks.high}`, bold: true, color: "FF4444" }),
        new TextRun({ text: `   |   ${l.medium}: ${risks.medium}`, bold: true, color: "FF9900" }),
        new TextRun({ text: `   |   ${l.low}: ${risks.low}`, bold: true, color: "44AA44" }),
      ],
      spacing: { after: 300 },
    })
  );

  // ─── Summary & Recommendation ─────────────────────────────────────────────
  if (report.summary) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: l.summary })],
        spacing: { before: 200, after: 100 },
      }),
      new Paragraph({
        children: [new TextRun({ text: report.summary })],
        spacing: { after: 200 },
      })
    );
  }

  if (report.recommendation) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: l.recommendation })],
        spacing: { before: 200, after: 100 },
      }),
      new Paragraph({
        children: [new TextRun({ text: report.recommendation })],
        spacing: { after: 300 },
      })
    );
  }

  // ─── Track Changes Note ────────────────────────────────────────────────────
  // ─── Deep analysis (Mike OS) ──────────────────────────────────────────────
  // The client pays for this layer; the DOCX is the artifact they keep and
  // forward, so it must carry it, not just the web report.
  {
    const rs = report.riskSummary as { negotiationChecklist?: string[] } | null;
    const checklist = Array.isArray(rs?.negotiationChecklist)
      ? rs!.negotiationChecklist!.filter((x: unknown) => typeof x === "string" && (x as string).trim())
      : [];
    const breakers: { title?: string; detail?: string }[] = Array.isArray(deep?.dealBreakers) ? deep.dealBreakers : [];
    const missing: { title?: string; detail?: string }[] = Array.isArray(deep?.missingProvisions) ? deep.missingProvisions : [];

    if (deep || checklist.length) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text: l.deepTitle })],
          spacing: { after: 100, before: 300 },
        })
      );
      if (deep?.riskScore) {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: `${l.deepScore}: ${Math.min(5, Math.max(1, Number(deep.riskScore) || 3))} / 5`, bold: true })],
            spacing: { after: 150 },
          })
        );
      }
      const pushList = (title: string, items: { title?: string; detail?: string }[], titleColor?: string) => {
        if (!items.length) return;
        children.push(
          new Paragraph({ children: [new TextRun({ text: title, bold: true })], spacing: { after: 80, before: 100 } })
        );
        for (const it of items) {
          const runs: TextRun[] = [];
          if (it?.title) runs.push(new TextRun({ text: `• ${it.title}`, bold: true, ...(titleColor ? { color: titleColor } : {}) }));
          if (it?.detail) runs.push(new TextRun({ text: `${it?.title ? ": " : "• "}${it.detail}` }));
          if (runs.length) children.push(new Paragraph({ children: runs, spacing: { after: 60 } }));
        }
      };
      pushList(l.dealBreakersTitle, breakers, "CC0000");
      pushList(l.missingTitle, missing);
      if (checklist.length) {
        children.push(
          new Paragraph({ children: [new TextRun({ text: l.checklistTitle, bold: true })], spacing: { after: 80, before: 100 } })
        );
        for (const item of checklist) {
          children.push(new Paragraph({ children: [new TextRun({ text: `• ${item}` })], spacing: { after: 60 } }));
        }
      }
      if (deep?.verificationNotes) {
        children.push(
          new Paragraph({ children: [new TextRun({ text: l.verificationNotesTitle, bold: true })], spacing: { after: 60, before: 100 } }),
          new Paragraph({ children: [new TextRun({ text: String(deep.verificationNotes), italics: true })], spacing: { after: 200 } })
        );
      }
    }
  }

  children.push(
    new Paragraph({
      children: [new TextRun({ text: l.trackChangesNote, italics: true, color: "555555", size: 18 })],
      spacing: { before: 200, after: 400 },
      border: {
        top: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
        bottom: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
        left: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
        right: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
      },
    })
  );

  // ─── Detailed Findings with Track Changes ──────────────────────────────────
  children.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: `${l.findings} (${sortedClauses.length})` })],
      spacing: { before: 400, after: 200 },
    })
  );

  let revisionId = 1;

  for (const clause of sortedClauses) {
    const effectiveRisk = clause.overriddenRiskLevel || clause.riskLevel;

    // Clause heading with risk badge
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_3,
        children: [
          new TextRun({ text: `${clause.clauseNumber}. ${clause.title}`, bold: true }),
          new TextRun({ text: `  [${l.riskLabels[effectiveRisk] || effectiveRisk}]`, color: riskColor(effectiveRisk), bold: true }),
        ],
        spacing: { before: 300, after: 100 },
      })
    );

    // Finding
    children.push(
      new Paragraph({
        children: [new TextRun({ text: clause.finding })],
        spacing: { after: 100 },
      })
    );

    // Legal basis
    if (clause.legalBasis) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${l.legalBasis}: `, bold: true, italics: true, size: 20 }),
            new TextRun({ text: clause.legalBasis, italics: true, size: 20, color: "444444" }),
          ],
          spacing: { after: 100 },
        })
      );
    }

    // ─── Track Changes: Original → Suggested Edit ────────────────────────────
    if (clause.excerpt && clause.suggestedEdit) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: "", size: 10 })],
          spacing: { after: 50 },
        })
      );

      // The paragraph with track changes: delete original, insert suggested
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${l.suggestedEdit}: `, bold: true, size: 20 }),
          ],
          spacing: { after: 50 },
        }),
        new Paragraph({
          children: [
            // Deleted (original text - shown as strikethrough in Word)
            new DeletedTextRun({
              text: clause.excerpt,
              id: revisionId++,
              author: AUTHOR,
              date: REVISION_DATE,
              color: "CC0000",
            }),
            new TextRun({ text: " " }),
            // Inserted (suggested edit - shown as underlined in Word)
            new InsertedTextRun({
              text: clause.suggestedEdit,
              id: revisionId++,
              author: AUTHOR,
              date: REVISION_DATE,
              color: "006600",
            }),
          ],
          spacing: { after: 150 },
          border: {
            left: { style: BorderStyle.SINGLE, size: 6, color: "DDDDDD" },
          },
        })
      );
    } else if (clause.suggestedEdit) {
      // Only suggested edit, no original excerpt
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${l.suggestedEdit}: `, bold: true, size: 20 }),
            new InsertedTextRun({
              text: clause.suggestedEdit,
              id: revisionId++,
              author: AUTHOR,
              date: REVISION_DATE,
            }),
          ],
          spacing: { after: 150 },
        })
      );
    }

    // Lawyer annotation
    if (clause.lawyerAnnotation) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${l.lawyerNote}: `, bold: true, italics: true }),
            new TextRun({ text: clause.lawyerAnnotation, italics: true }),
          ],
          spacing: { after: 200 },
        })
      );
    }
  }

  // ─── Disclaimer ────────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      children: [new TextRun({ text: "" })],
      spacing: { before: 400 },
    }),
    new Paragraph({
      children: [new TextRun({ text: isSigned ? l.disclaimer : l.disclaimerUnsigned, italics: true, size: 18, color: "888888" })],
      spacing: { after: 50 },
    }),
    new Paragraph({
      children: [new TextRun({ text: l.company, size: 16, color: "888888" })],
    })
  );

  // ─── Create Document ───────────────────────────────────────────────────────
  const doc = new Document({
    // Machine-readable AI marking per art. 50(2) of Regulation (EU) 2024/1689.
    title: `bod.legal report: ${contract.fileName || "zmluva"}`,
    description: aiOutputStatement(isSigned),
    creator: AI_MARKING_CREATOR,
    keywords: AI_MARKING_KEYWORDS,
    features: {
      trackRevisions: true,
    },
    styles: {
      default: {
        document: {
          run: { font: "Calibri", size: 22 },
        },
        heading1: {
          run: { font: "Georgia", size: 32, bold: true },
        },
        heading2: {
          run: { font: "Georgia", size: 26, bold: true },
        },
        heading3: {
          run: { font: "Georgia", size: 24, bold: true },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
          },
        },
        headers: {
          default: buildPageHeader(l, isSigned),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: "bod.legal | KILIAN LEGAL s.r.o. | ", size: 16, color: "999999" }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 16, color: "999999" }),
                  new TextRun({ text: "/", size: 16, color: "999999" }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: "999999" }),
                ],
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return buffer as Buffer;
}

/**
 * Register the DOCX export route.
 * GET /api/contracts/:id/report.docx?lang=sk|en
 * Requires authentication. Only the contract owner or admin can download.
 */
/**
 * Generate a clean DOCX (no track changes) with decisions applied.
 */
async function generateFinalDocx(
  contract: any,
  clauses: any[],
  report: any,
  decisions: Record<string, "accepted" | "rejected">,
  lang: Lang
): Promise<Buffer> {
  const l = LABELS[lang];
  // Verification is only claimed once the lawyer signed the report.
  const isSigned = !!report.isSigned;
  const planLabel = l.planLabels[contract.plan] || contract.plan;
  const dateStr = new Date(contract.createdAt).toLocaleDateString(lang === "sk" ? "sk-SK" : "en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  const sortedClauses = [...clauses].sort((a, b) => a.clauseNumber - b.clauseNumber);

  const children: Paragraph[] = [];

  // Title
  children.push(
    new Paragraph({
      children: [new TextRun({ text: l.finalTitle, bold: true, size: 48, font: "Georgia" })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [new TextRun({ text: l.finalSubtitle, size: 20, color: "666666" })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    })
  );

  // Metadata
  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: `${l.document}: `, bold: true }),
        new TextRun({ text: contract.fileName || "…" }),
      ],
      spacing: { after: 80 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `${l.date}: `, bold: true }),
        new TextRun({ text: dateStr }),
      ],
      spacing: { after: 200 },
    })
  );

  // Note
  children.push(
    new Paragraph({
      children: [new TextRun({ text: l.finalNote, italics: true, color: "555555", size: 20 })],
      spacing: { before: 100, after: 300 },
      border: {
        top: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
        bottom: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
        left: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
        right: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
      },
    })
  );

  // Clauses with decisions applied
  children.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: l.findings })],
      spacing: { before: 300, after: 200 },
    })
  );

  for (const clause of sortedClauses) {
    const decision = decisions[String(clause.id)];
    const effectiveRisk = clause.overriddenRiskLevel || clause.riskLevel;

    // Clause heading
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_3,
        children: [
          new TextRun({ text: `${clause.clauseNumber}. ${clause.title}`, bold: true }),
          new TextRun({ text: `  [${l.riskLabels[effectiveRisk] || effectiveRisk}]`, color: riskColor(effectiveRisk), bold: true }),
        ],
        spacing: { before: 300, after: 100 },
      })
    );

    // Determine final text for this clause
    let finalText: string;
    if (clause.suggestedEdit && decision === "accepted") {
      finalText = clause.suggestedEdit;
    } else {
      finalText = clause.excerpt || clause.finding;
    }

    // Clause text label + content
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: `${l.clauseText}: `, bold: true, size: 20 }),
        ],
        spacing: { after: 50 },
      }),
      new Paragraph({
        children: [new TextRun({ text: finalText })],
        spacing: { after: 100 },
        border: {
          left: { style: BorderStyle.SINGLE, size: 6, color: decision === "accepted" ? "44AA44" : "DDDDDD" },
        },
      })
    );

    // Finding
    children.push(
      new Paragraph({
        children: [new TextRun({ text: clause.finding, color: "444444", size: 20 })],
        spacing: { after: 100 },
      })
    );

    // Legal basis
    if (clause.legalBasis) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${l.legalBasis}: `, bold: true, italics: true, size: 20 }),
            new TextRun({ text: clause.legalBasis, italics: true, size: 20, color: "444444" }),
          ],
          spacing: { after: 100 },
        })
      );
    }

    // Lawyer annotation
    if (clause.lawyerAnnotation) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${l.lawyerNote}: `, bold: true, italics: true }),
            new TextRun({ text: clause.lawyerAnnotation, italics: true }),
          ],
          spacing: { after: 200 },
        })
      );
    }
  }

  // Disclaimer
  children.push(
    new Paragraph({ children: [new TextRun({ text: "" })], spacing: { before: 400 } }),
    new Paragraph({
      children: [new TextRun({ text: isSigned ? l.disclaimer : l.disclaimerUnsigned, italics: true, size: 18, color: "888888" })],
      spacing: { after: 50 },
    }),
    new Paragraph({
      children: [new TextRun({ text: l.company, size: 16, color: "888888" })],
    })
  );

  const doc = new Document({
    // The final version is assembled from AI-proposed clause wordings, so it
    // carries the same art. 50(2) machine-readable marking as the report.
    title: `bod.legal finalna verzia: ${contract.fileName || "zmluva"}`,
    description: aiOutputStatement(isSigned),
    creator: AI_MARKING_CREATOR,
    keywords: AI_MARKING_KEYWORDS,
    features: { trackRevisions: false },
    styles: {
      default: {
        document: { run: { font: "Calibri", size: 22 } },
        heading1: { run: { font: "Georgia", size: 32, bold: true } },
        heading2: { run: { font: "Georgia", size: 26, bold: true } },
        heading3: { run: { font: "Georgia", size: 24, bold: true } },
      },
    },
    sections: [{
      properties: {
        page: { margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } },
      },
      headers: {
        default: buildPageHeader(l, isSigned),
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              children: [
                new TextRun({ text: "bod.legal | KILIAN LEGAL s.r.o. | ", size: 16, color: "999999" }),
                new TextRun({ children: [PageNumber.CURRENT], size: 16, color: "999999" }),
                new TextRun({ text: "/", size: 16, color: "999999" }),
                new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: "999999" }),
              ],
              alignment: AlignmentType.CENTER,
            }),
          ],
        }),
      },
      children,
    }],
  });

  const buffer = await Packer.toBuffer(doc);
  return buffer as Buffer;
}

export function registerDocxExport(app: Express) {
  app.get("/api/contracts/:id/report.docx", async (req: Request, res: Response) => {
    try {
      // Authenticate the request
      const user = await sdk.authenticateRequest(req);
      if (!user) {
        res.status(401).json({ error: "Unauthorized" });
        return;
      }

      const contractId = parseInt(req.params.id);
      if (isNaN(contractId)) {
        res.status(400).json({ error: "Invalid contract ID" });
        return;
      }

      // Determine language
      const lang: Lang = req.query.lang === "en" ? "en" : "sk";

      // Fetch contract data
      const contract = await getContractById(contractId);
      if (!contract) {
        res.status(404).json({ error: "Contract not found" });
        return;
      }

      // Authorization: owner or admin only
      if (contract.userId !== user.id && user.role !== "admin") {
        res.status(403).json({ error: "Forbidden" });
        return;
      }

      // Basic plan users cannot download DOCX
      if (contract.plan === "basic") {
        res.status(403).json({ error: "DOCX export is not available for the basic plan" });
        return;
      }

      const clauses = (await getClausesByContractId(contractId)).filter(c => !isClauseExcluded(c));
      const report = await getReportByContractId(contractId);

      if (!report) {
        res.status(404).json({ error: "Report not found" });
        return;
      }

      const deep = await getDeepAnalysisByContract(contractId).catch(() => null);
      const buffer = await generateReportDocx(contract, clauses, report, lang, deep);

      const filename = `bod-legal-report-${contractId}-${lang}.docx`;
      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
      res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
      res.setHeader("Content-Length", buffer.length.toString());
      res.send(buffer);
    } catch (error: any) {
      console.error("[DOCX Export] Error:", error);
      res.status(500).json({ error: "Failed to generate DOCX" });
    }
  });

  // ─── Final version (clean DOCX with decisions applied) ──────────────────────
  // POST /api/contracts/:id/report-final.docx
  // Body: { decisions: Record<clauseId, 'accepted'|'rejected'>, lang?: 'sk'|'en' }
  app.post("/api/contracts/:id/report-final.docx", async (req: Request, res: Response) => {
    try {
      const user = await sdk.authenticateRequest(req);
      if (!user) {
        res.status(401).json({ error: "Unauthorized" });
        return;
      }

      const contractId = parseInt(req.params.id);
      if (isNaN(contractId)) {
        res.status(400).json({ error: "Invalid contract ID" });
        return;
      }

      const { decisions, lang: reqLang } = req.body || {};
      const lang: Lang = reqLang === "en" ? "en" : "sk";

      if (!decisions || typeof decisions !== "object") {
        res.status(400).json({ error: "Missing decisions object" });
        return;
      }

      const contract = await getContractById(contractId);
      if (!contract) {
        res.status(404).json({ error: "Contract not found" });
        return;
      }

      if (contract.userId !== user.id && user.role !== "admin") {
        res.status(403).json({ error: "Forbidden" });
        return;
      }

      if (contract.plan === "basic") {
        res.status(403).json({ error: "Final DOCX export is not available for the basic plan" });
        return;
      }

      const clauses = (await getClausesByContractId(contractId)).filter(c => !isClauseExcluded(c));
      const report = await getReportByContractId(contractId);

      if (!report) {
        res.status(404).json({ error: "Report not found" });
        return;
      }

      const buffer = await generateFinalDocx(contract, clauses, report, decisions, lang);

      const filename = `bod-legal-final-${contractId}-${lang}.docx`;
      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
      res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
      res.setHeader("Content-Length", buffer.length.toString());
      res.send(buffer);
    } catch (error: any) {
      console.error("[DOCX Final Export] Error:", error);
      res.status(500).json({ error: "Failed to generate final DOCX" });
    }
  });
}
