import type { Express, Request, Response } from "express";
import { jsPDF } from "jspdf";
import QRCode from "qrcode";
import { sdk } from "./_core/sdk";
import { invokeLLM } from "./_core/llm";
import { getContractById, getClausesByContractId, getReportByContractId, isClauseExcluded } from "./db";
import { getInterRegularBase64, getInterBoldBase64 } from "./fonts/font-data";
import { signOffLines } from "@shared/advokat";
import { aiOutputStatement, AI_MARKING_KEYWORDS, AI_MARKING_CREATOR } from "@shared/aiMarking";

type Lang = "sk" | "en";

// ─── Localized labels ────────────────────────────────────────────────────────

const LABELS = {
  sk: {
    subtitle: "Analýza zmluvy | AI + overenie advokátom",
    subtitleUnsigned: "Analýza zmluvy | Pracovná verzia, čaká na overenie advokátom",
    document: "Dokument:",
    plan: "Plán:",
    date: "Dátum:",
    verifiedBy: "Overil:",
    riskSummaryTitle: "Sumár rizík",
    riskHigh: "Vysoké",
    riskMedium: "Stredné",
    riskLow: "Nízke",
    summaryTitle: "Zhrnutie",
    recommendationTitle: "Odporúčanie",
    executiveSummaryTitle: "Manažérske zhrnutie",
    findingsTitle: (n: number) => `Detailné nálezy (${n} klauzúl)`,
    legalBasis: "Právny základ:",
    suggestedEdit: "Navrhovaná úprava:",
    lawyerNote: "Poznámka advokáta:",
    disclaimer: "Tento report bol vygenerovaný systémom bod.legal s využitím AI a overený advokátom.",
    disclaimerUnsigned: "Tento report vygenerovala AI systému bod.legal a čaká na overenie advokátom.",
    draftWatermark: "PRACOVNÁ VERZIA",
    company: "Prevádzkované KILIAN LEGAL s.r.o. | IČO: 53 957 008 | info@bod.legal",
    qrTitle: "Overenie reportu online",
    qrDesc: "Naskenujte QR kód pre prístup k interaktívnej verzii tohto reportu.",
    pageFooter: (i: number, total: number) => `bod.legal | KILIAN LEGAL s.r.o. | Strana ${i} z ${total}`,
    dateLocale: "sk-SK",
    planLabels: {
      basic: "Základná kontrola",
      standard: "Štandardná kontrola",
      premium: "Prémiová kontrola",
    } as Record<string, string>,
    riskLabels: {
      high: "Vysoké riziko",
      medium: "Stredné riziko",
      low: "Nízke riziko",
    } as Record<string, string>,
  },
  en: {
    subtitle: "Contract Analysis | AI + Lawyer Verification",
    subtitleUnsigned: "Contract Analysis | Draft version, awaiting lawyer verification",
    document: "Document:",
    plan: "Plan:",
    date: "Date:",
    verifiedBy: "Verified by:",
    riskSummaryTitle: "Risk Summary",
    riskHigh: "High",
    riskMedium: "Medium",
    riskLow: "Low",
    summaryTitle: "Summary",
    recommendationTitle: "Recommendation",
    executiveSummaryTitle: "Executive Summary",
    findingsTitle: (n: number) => `Detailed Findings (${n} clauses)`,
    legalBasis: "Legal basis:",
    suggestedEdit: "Suggested edit:",
    lawyerNote: "Lawyer note:",
    disclaimer: "This report was generated by bod.legal using AI and verified by a lawyer.",
    disclaimerUnsigned: "This report was generated by the bod.legal AI system and is awaiting verification by a lawyer.",
    draftWatermark: "DRAFT VERSION",
    company: "Operated by KILIAN LEGAL s.r.o. | ID: 53 957 008 | info@bod.legal",
    qrTitle: "Verify report online",
    qrDesc: "Scan the QR code to access the interactive version of this report.",
    pageFooter: (i: number, total: number) => `bod.legal | KILIAN LEGAL s.r.o. | Page ${i} of ${total}`,
    dateLocale: "en-GB",
    planLabels: {
      basic: "Basic Review",
      standard: "Standard Review",
      premium: "Premium Review",
    } as Record<string, string>,
    riskLabels: {
      high: "High risk",
      medium: "Medium risk",
      low: "Low risk",
    } as Record<string, string>,
  },
};

/**
 * Register the PDF export route.
 * GET /api/contracts/:id/report.pdf?lang=sk|en
 * Requires authentication. Only the contract owner or admin can download.
 */
export function registerPdfExport(app: Express) {
  app.get("/api/contracts/:id/report.pdf", async (req: Request, res: Response) => {
    try {
      // Authenticate the request
      const user = await sdk.authenticateRequest(req);
      if (!user) {
        res.status(401).json({ error: "Unauthorized" });
        return;
      }

      const contractId = parseInt(req.params.id);
      if (isNaN(contractId)) {
        res.status(400).json({ error: "Invalid contract ID" });
        return;
      }

      // Determine language
      const lang: Lang = req.query.lang === "en" ? "en" : "sk";

      // Fetch contract data
      const contract = await getContractById(contractId);
      if (!contract) {
        res.status(404).json({ error: "Contract not found" });
        return;
      }

      // Authorization: owner or admin only
      if (contract.userId !== user.id && user.role !== "admin") {
        res.status(403).json({ error: "Forbidden" });
        return;
      }

      // Basic plan users cannot download PDF (limited preview only)
      if (contract.plan === "basic") {
        res.status(403).json({ error: "PDF export is not available for the basic plan" });
        return;
      }

      const clauses = (await getClausesByContractId(contractId)).filter(c => !isClauseExcluded(c));
      const report = await getReportByContractId(contractId);

      if (!report) {
        res.status(404).json({ error: "Report not yet available" });
        return;
      }

      // Generate AI executive summary
      let executiveSummary: string | null = null;
      try {
        executiveSummary = await generateExecutiveSummary(contract, clauses, report, lang);
      } catch (llmErr) {
        console.warn("[PDF Export] Executive summary generation failed:", llmErr);
        // Continue without executive summary - non-critical feature
      }

      // Generate PDF with online report URL for QR code (locale-aware)
      const origin = req.headers.origin || `${req.protocol}://${req.headers.host}`;
      const reportUrl = lang === "en" ? `${origin}/en/report/${contractId}` : `${origin}/report/${contractId}`;
      const pdf = await generateReportPdf(contract, clauses, report, reportUrl, lang, executiveSummary);
      const pdfBuffer = Buffer.from(pdf.output("arraybuffer"));

      // Send PDF response
      const safeFileName = contract.fileName
        .replace(/\.[^.]+$/, "") // remove extension
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "") // strip diacritics for filename
        .replace(/[^a-zA-Z0-9._-]/g, "_")
        .replace(/_+/g, "_");

      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", `attachment; filename="bod-legal_report_${safeFileName}.pdf"`);
      res.setHeader("Content-Length", pdfBuffer.length.toString());
      res.send(pdfBuffer);
    } catch (err: any) {
      console.error("[PDF Export] Error:", err);
      res.status(500).json({ error: "Failed to generate PDF" });
    }
  });
}

// ─── AI Executive Summary Generation ─────────────────────────────────────────

async function generateExecutiveSummary(
  contract: any,
  clauses: any[],
  report: any,
  lang: Lang
): Promise<string> {
  const riskSummary = report.riskSummary as { high: number; medium: number; low: number } | null;
  const highRiskClauses = clauses.filter(c => (c.overriddenRiskLevel || c.riskLevel) === "high");
  const clauseSummaries = highRiskClauses
    .slice(0, 5)
    .map(c => `- ${c.title}: ${c.finding}`)
    .join("\n");

  const systemPrompt = lang === "en"
    ? `You are a senior legal analyst. Write a concise executive summary (3-5 sentences, max 150 words) for a contract analysis report. Focus on: (1) overall risk assessment, (2) most critical issues, (3) actionable recommendation. Write in professional English. Do not use markdown formatting.`
    : `Si skúsený právny analytik. Napíš stručné manažérske zhrnutie (3-5 viet, max 150 slov) pre report z analýzy zmluvy. Zameraj sa na: (1) celkové hodnotenie rizík, (2) najkritickejšie problémy, (3) odporúčanie na ďalší postup. Píš profesionálnou slovenčinou. Nepoužívaj markdown formátovanie.`;

  const userPrompt = lang === "en"
    ? `Contract: "${contract.fileName}"
Plan: ${contract.plan}
Risk summary: ${riskSummary ? `${riskSummary.high} high, ${riskSummary.medium} medium, ${riskSummary.low} low risk findings` : "N/A"}
Total clauses analyzed: ${clauses.length}
Report summary: ${report.summary || "N/A"}
Recommendation: ${report.recommendation || "N/A"}
Top high-risk findings:
${clauseSummaries || "None"}

Write the executive summary:`
    : `Zmluva: "${contract.fileName}"
Plán: ${contract.plan}
Sumár rizík: ${riskSummary ? `${riskSummary.high} vysoké, ${riskSummary.medium} stredné, ${riskSummary.low} nízke riziko` : "N/A"}
Celkom analyzovaných klauzúl: ${clauses.length}
Zhrnutie reportu: ${report.summary || "N/A"}
Odporúčanie: ${report.recommendation || "N/A"}
Najrizikovejšie nálezy:
${clauseSummaries || "Žiadne"}

Napíš manažérske zhrnutie:`;

  const result = await invokeLLM({
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ],
    max_tokens: 300,
  });

  const content = result.choices?.[0]?.message?.content;
  if (typeof content === "string") {
    return content.trim();
  }
  if (Array.isArray(content)) {
    const textPart = content.find((c: any) => c.type === "text");
    return (textPart as any)?.text?.trim() || "";
  }
  return "";
}

// ─── PDF Generation Logic ──────────────────────────────────────────────────

async function generateReportPdf(
  contract: any,
  clauses: any[],
  report: any,
  reportUrl: string,
  lang: Lang,
  executiveSummary: string | null
): Promise<jsPDF> {
  const L = LABELS[lang];
  // Verification is only claimed once the lawyer signed the report.
  const isSigned = !!report.isSigned;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  // Machine-readable AI marking per art. 50(2) of Regulation (EU) 2024/1689;
  // our Transparentnost AI document promises exactly this.
  doc.setDocumentProperties({
    title: `bod.legal report: ${contract.fileName || "zmluva"}`,
    subject: aiOutputStatement(isSigned),
    author: AI_MARKING_CREATOR,
    keywords: AI_MARKING_KEYWORDS,
    creator: AI_MARKING_CREATOR,
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // ─── Embed Unicode fonts ─────────────────────────────────────────────────
  const interRegular = getInterRegularBase64();
  const interBold = getInterBoldBase64();
  doc.addFileToVFS("Inter-Regular.ttf", interRegular);
  doc.addFileToVFS("Inter-Bold.ttf", interBold);
  doc.addFont("Inter-Regular.ttf", "Inter", "normal");
  doc.addFont("Inter-Bold.ttf", "Inter", "bold");
  doc.setFont("Inter", "normal");

  // Helper: check if we need a new page
  function checkPage(neededHeight: number) {
    if (y + neededHeight > pageHeight - 25) {
      doc.addPage();
      y = margin;
    }
  }

  // ─── Header / Title ────────────────────────────────────────────────────────
  doc.setFontSize(22);
  doc.setFont("Inter", "bold");
  doc.text("bod.legal", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("Inter", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(isSigned ? L.subtitle : L.subtitleUnsigned, margin, y);
  doc.setTextColor(0, 0, 0);
  y += 12;

  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // ─── Contract Info ─────────────────────────────────────────────────────────
  doc.setFontSize(11);
  doc.setFont("Inter", "bold");
  doc.text(L.document, margin, y);
  doc.setFont("Inter", "normal");
  doc.text(contract.fileName || "…", margin + 28, y);
  y += 6;

  doc.setFont("Inter", "bold");
  doc.text(L.plan, margin, y);
  doc.setFont("Inter", "normal");
  doc.text(L.planLabels[contract.plan] || contract.plan, margin + 28, y);
  y += 6;

  doc.setFont("Inter", "bold");
  doc.text(L.date, margin, y);
  doc.setFont("Inter", "normal");
  doc.text(
    contract.createdAt ? new Date(contract.createdAt).toLocaleDateString(L.dateLocale) : "…",
    margin + 28,
    y
  );
  y += 6;

  if (report.isSigned && report.lawyerName) {
    doc.setFont("Inter", "bold");
    doc.text(L.verifiedBy, margin, y);
    doc.setFont("Inter", "normal");
    const signLines = signOffLines(report.lawyerName, lang);
    const signDate = report.signedAt ? ` (${new Date(report.signedAt).toLocaleDateString(L.dateLocale)})` : "";
    doc.text(`${signLines[0]}${signDate}`, margin + 28, y);
    for (const extra of signLines.slice(1)) {
      y += 5;
      doc.text(extra, margin + 28, y);
    }
    y += 6;
  }
  y += 8;

  // ─── Executive Summary (AI-generated) ─────────────────────────────────────
  if (executiveSummary) {
    checkPage(40);

    // Highlighted box background
    doc.setFillColor(245, 245, 240);
    const summaryLines = doc.splitTextToSize(executiveSummary, contentWidth - 16);
    const boxHeight = 12 + summaryLines.length * 5 + 4;
    doc.roundedRect(margin, y - 2, contentWidth, boxHeight, 2, 2, "F");

    doc.setFontSize(12);
    doc.setFont("Inter", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text(L.executiveSummaryTitle, margin + 8, y + 6);
    y += 12;

    doc.setFontSize(10);
    doc.setFont("Inter", "normal");
    doc.setTextColor(50, 50, 50);
    for (const line of summaryLines) {
      doc.text(line, margin + 8, y);
      y += 5;
    }
    doc.setTextColor(0, 0, 0);
    y += 10;
  }

  // ─── Risk Summary ─────────────────────────────────────────────────────────
  const riskSummary = report.riskSummary as { high: number; medium: number; low: number } | null;
  if (riskSummary) {
    checkPage(20);
    doc.setFontSize(14);
    doc.setFont("Inter", "bold");
    doc.text(L.riskSummaryTitle, margin, y);
    y += 8;

    doc.setFontSize(11);
    doc.setFont("Inter", "normal");

    // Risk boxes
    const boxWidth = (contentWidth - 10) / 3;
    const boxHeight = 14;

    // High risk box
    doc.setFillColor(254, 226, 226);
    doc.roundedRect(margin, y, boxWidth, boxHeight, 2, 2, "F");
    doc.setTextColor(153, 27, 27);
    doc.setFont("Inter", "bold");
    doc.text(`${riskSummary.high}`, margin + boxWidth / 2, y + 6, { align: "center" });
    doc.setFontSize(8);
    doc.setFont("Inter", "normal");
    doc.text(L.riskHigh, margin + boxWidth / 2, y + 11, { align: "center" });

    // Medium risk box
    doc.setFillColor(254, 243, 199);
    doc.roundedRect(margin + boxWidth + 5, y, boxWidth, boxHeight, 2, 2, "F");
    doc.setTextColor(146, 64, 14);
    doc.setFont("Inter", "bold");
    doc.setFontSize(11);
    doc.text(`${riskSummary.medium}`, margin + boxWidth + 5 + boxWidth / 2, y + 6, { align: "center" });
    doc.setFontSize(8);
    doc.setFont("Inter", "normal");
    doc.text(L.riskMedium, margin + boxWidth + 5 + boxWidth / 2, y + 11, { align: "center" });

    // Low risk box
    doc.setFillColor(220, 252, 231);
    doc.roundedRect(margin + (boxWidth + 5) * 2, y, boxWidth, boxHeight, 2, 2, "F");
    doc.setTextColor(22, 101, 52);
    doc.setFont("Inter", "bold");
    doc.setFontSize(11);
    doc.text(`${riskSummary.low}`, margin + (boxWidth + 5) * 2 + boxWidth / 2, y + 6, { align: "center" });
    doc.setFontSize(8);
    doc.setFont("Inter", "normal");
    doc.text(L.riskLow, margin + (boxWidth + 5) * 2 + boxWidth / 2, y + 11, { align: "center" });

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    y += boxHeight + 10;
  }

  // ─── Summary ──────────────────────────────────────────────────────────────
  if (report.summary) {
    checkPage(30);
    doc.setFontSize(14);
    doc.setFont("Inter", "bold");
    doc.text(L.summaryTitle, margin, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont("Inter", "normal");
    const summaryLines = doc.splitTextToSize(report.summary, contentWidth);
    for (const line of summaryLines) {
      checkPage(6);
      doc.text(line, margin, y);
      y += 5;
    }
    y += 8;
  }

  // ─── Recommendation ───────────────────────────────────────────────────────
  if (report.recommendation) {
    checkPage(30);
    doc.setFontSize(14);
    doc.setFont("Inter", "bold");
    doc.text(L.recommendationTitle, margin, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont("Inter", "normal");
    const recLines = doc.splitTextToSize(report.recommendation, contentWidth);
    for (const line of recLines) {
      checkPage(6);
      doc.text(line, margin, y);
      y += 5;
    }
    y += 8;
  }

  // ─── Clause Findings ──────────────────────────────────────────────────────
  if (clauses && clauses.length > 0) {
    checkPage(20);
    doc.setFontSize(14);
    doc.setFont("Inter", "bold");
    doc.text(L.findingsTitle(clauses.length), margin, y);
    y += 10;

    for (const clause of clauses) {
      const effectiveRisk = clause.overriddenRiskLevel || clause.riskLevel;
      const estimatedHeight = 30 + (clause.excerpt ? 15 : 0) + (clause.suggestedEdit ? 15 : 0) + (clause.lawyerAnnotation ? 15 : 0);
      checkPage(estimatedHeight);

      // Clause header with risk badge
      doc.setFontSize(11);
      doc.setFont("Inter", "bold");
      doc.text(`#${clause.clauseNumber} ${clause.title}`, margin, y);

      // Risk label on the right
      doc.setFontSize(9);
      doc.setFont("Inter", "normal");
      const riskLabel = L.riskLabels[effectiveRisk] || effectiveRisk;
      if (effectiveRisk === "high") doc.setTextColor(153, 27, 27);
      else if (effectiveRisk === "medium") doc.setTextColor(146, 64, 14);
      else doc.setTextColor(22, 101, 52);
      doc.text(riskLabel, pageWidth - margin, y, { align: "right" });
      doc.setTextColor(0, 0, 0);
      y += 6;

      // Excerpt
      if (clause.excerpt) {
        doc.setFontSize(9);
        doc.setFont("Inter", "normal");
        doc.setTextColor(100, 100, 100);
        const excerptLines = doc.splitTextToSize(`\u201E${clause.excerpt}\u201C`, contentWidth - 5);
        for (const line of excerptLines.slice(0, 3)) {
          checkPage(5);
          doc.text(line, margin + 3, y);
          y += 4.5;
        }
        doc.setTextColor(0, 0, 0);
        y += 2;
      }

      // Finding
      doc.setFontSize(10);
      doc.setFont("Inter", "normal");
      const findingLines = doc.splitTextToSize(clause.finding, contentWidth - 3);
      for (const line of findingLines) {
        checkPage(5);
        doc.text(line, margin + 3, y);
        y += 5;
      }
      y += 2;

      // Legal basis
      if (clause.legalBasis) {
        checkPage(6);
        doc.setFontSize(9);
        doc.setTextColor(80, 80, 80);
        doc.text(`${L.legalBasis} ${clause.legalBasis}`, margin + 3, y);
        doc.setTextColor(0, 0, 0);
        y += 5;
      }

      // Suggested edit
      if (clause.suggestedEdit) {
        checkPage(12);
        doc.setFontSize(9);
        doc.setFont("Inter", "bold");
        doc.text(L.suggestedEdit, margin + 3, y);
        y += 4.5;
        doc.setFont("Inter", "normal");
        const editLines = doc.splitTextToSize(clause.suggestedEdit, contentWidth - 8);
        for (const line of editLines.slice(0, 4)) {
          checkPage(5);
          doc.text(line, margin + 5, y);
          y += 4.5;
        }
        y += 2;
      }

      // Lawyer annotation
      if (clause.lawyerAnnotation) {
        checkPage(12);
        doc.setFontSize(9);
        doc.setFont("Inter", "bold");
        doc.setTextColor(146, 64, 14);
        doc.text(L.lawyerNote, margin + 3, y);
        y += 4.5;
        doc.setFont("Inter", "normal");
        doc.setTextColor(0, 0, 0);
        const annotLines = doc.splitTextToSize(clause.lawyerAnnotation, contentWidth - 8);
        for (const line of annotLines.slice(0, 4)) {
          checkPage(5);
          doc.text(line, margin + 5, y);
          y += 4.5;
        }
        y += 2;
      }

      // Separator between clauses
      y += 3;
      doc.setDrawColor(230, 230, 230);
      doc.setLineWidth(0.2);
      doc.line(margin, y, pageWidth - margin, y);
      y += 6;
    }
  }

  // ─── Disclaimer Footer ────────────────────────────────────────────────────
  checkPage(25);
  y += 5;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(isSigned ? L.disclaimer : L.disclaimerUnsigned, pageWidth / 2, y, { align: "center" });
  y += 4;
  doc.text(L.company, pageWidth / 2, y, { align: "center" });

  // ─── QR Code Page ──────────────────────────────────────────────────────────
  checkPage(60);
  y += 10;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;

  doc.setFontSize(11);
  doc.setFont("Inter", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text(L.qrTitle, pageWidth / 2, y, { align: "center" });
  y += 6;

  doc.setFontSize(9);
  doc.setFont("Inter", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(L.qrDesc, pageWidth / 2, y, { align: "center" });
  y += 10;

  // Generate QR code as data URL and embed it
  try {
    const qrDataUrl = await QRCode.toDataURL(reportUrl, {
      width: 200,
      margin: 1,
      color: { dark: "#1a1a1a", light: "#ffffff" },
    });
    const qrSize = 35;
    const qrX = (pageWidth - qrSize) / 2;
    doc.addImage(qrDataUrl, "PNG", qrX, y, qrSize, qrSize);
    y += qrSize + 6;
  } catch (qrErr) {
    // Fallback: log error and print URL text instead of QR image
    console.warn("[PDF Export] QR code generation failed:", qrErr);
    y += 5;
  }

  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(reportUrl, pageWidth / 2, y, { align: "center" });
  doc.setTextColor(0, 0, 0);

  // ─── Add watermark and footer to all pages ─────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    // Diagonal watermark
    doc.saveGraphicsState();
    // @ts-ignore - setGState is available in jsPDF
    const gState = new (doc as any).GState({ opacity: 0.04 });
    // @ts-ignore
    doc.setGState(gState);
    doc.setFontSize(60);
    doc.setFont("Inter", "bold");
    doc.setTextColor(0, 0, 0);
    // Rotate text diagonally across the page
    const centerX = pageWidth / 2;
    const centerY = pageHeight / 2;
    doc.text("bod.legal", centerX, centerY, {
      align: "center",
      angle: 45,
    });
    doc.restoreGraphicsState();

    // Unsigned reports carry an additional, clearly visible draft watermark.
    if (!isSigned) {
      doc.saveGraphicsState();
      // @ts-ignore - setGState is available in jsPDF
      const draftGState = new (doc as any).GState({ opacity: 0.12 });
      // @ts-ignore
      doc.setGState(draftGState);
      doc.setFontSize(38);
      doc.setFont("Inter", "bold");
      doc.setTextColor(0, 0, 0);
      doc.text(L.draftWatermark, centerX, centerY + 30, {
        align: "center",
        angle: 45,
      });
      doc.restoreGraphicsState();
    }

    // Page footer
    doc.setFontSize(8);
    doc.setFont("Inter", "normal");
    doc.setTextColor(150, 150, 150);
    doc.text(
      L.pageFooter(i, totalPages),
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
  }

  return doc;
}
